# BEGIN ANSIBLE MANAGED BLOCK
bgp_asn: 65004
bgp_peers:
    - peer: spine01
      peer_ip: 172.31.1.6
      remote_as: 65101
    - peer: spine02
      peer_ip: 172.31.1.16
      remote_as: 65102
# END ANSIBLE MANAGED BLOCK
