# BEGIN ANSIBLE MANAGED BLOCK
bgp_asn: 65003
bgp_peers:
    - peer: spine01
      peer_ip: 172.31.1.4
      remote_as: 65100
    - peer: spine02
      peer_ip: 172.31.1.14
      remote_as: 65100

# END ANSIBLE MANAGED BLOCK
