---
- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  become: yes

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo
  become: yes

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  # when: node_repo.changed
  become: yes
  # tags: ['skip_ansible_lint']

- name: Install Nodejs and NPM.
  apt: #"name=nodejs={{ nodejs_version|regex_replace('x', '') }}* state=present"
    name: "{{ item.name }}={{ item.version | regex_replace('x','') }}*"
    state: present
  loop: "{{ packages }}"
  become: yes
