---
netbox_url: http://172.20.100.32:8080
netbox_token: e3afd6708f2a6cb45413c31c713ce6a146d69075

sites:
  - name: DC1
    description: "Main Data Center in Sydney"
    location: Sydney
  - name: DC2
    description: "Main Data Center in KSA"
    location: Riyadh

devices:
  - role: Leaf_Switch
    type: 7020SR
    vendor: Arista
    color: 'f44336'  # red
  - role: Spine_Switch
    type: 7050CX3
    ru: 2
    vendor: Arista
    color: '2196f3'  # blue

# BEGIN ANSIBLE MANAGED BLOCK
global: 
  bgp_asn: 65000
  mgmt_gw: 172.20.1.33
  mgmt_prefix: 28
  mgmt_prefixes:
  - 10.8.0.0/24
  - 172.20.1.0/24
  - 192.168.0.0/24
  mgmt_vrf: MGMT
  p2p_prefix: 31
  users:
  -   name: ansible
      password: ansible123
      privilege: 15
      role: network-admin


subnets:
  -   prefix: 172.10.1.0/24
      role: p2p_subnet
      # site: dc1
  -   prefix: 172.11.1.0/24
      role: p2p_subnet
      # site: dc2
  -   prefix: 10.100.1.0/24
      role: loopback_subnet
      site: dc1
  -   prefix: 10.100.2.0/24
      role: loopback_subnet
      site: dc2
  -   prefix: 172.20.1.0/24
      role: oob_mgmt_subnet
      site: dc1
  -   prefix: 172.20.2.0/24
      role: oob_mgmt_subnet
      site: dc2


p2p_ip:
  dc1-leaf01:
    - {port: Ethernet8, ip: 172.10.1.1/31 , peer: dc1-spine01, pport: Ethernet1, peer_ip: 172.10.1.0/31}
    - {port: Ethernet9, ip: 172.10.1.5/31 , peer: dc1-spine02, pport: Ethernet1, peer_ip: 172.10.1.4/31}
  dc1-leaf02:
    - {port: Ethernet8, ip: 172.10.1.3/31 , peer: dc1-spine01, pport: Ethernet2, peer_ip: 172.10.1.2/31}
    - {port: Ethernet9, ip: 172.10.1.7/31 , peer: dc1-spine02, pport: Ethernet2, peer_ip: 172.10.1.6/31}
  dc1-spine01:
    - {port: Ethernet1, ip: 172.10.1.0/31 , peer: dc1-leaf01, pport: Ethernet8, peer_ip: 172.10.1.1/31}
    - {port: Ethernet2, ip: 172.10.1.2/31 , peer: dc1-leaf02, pport: Ethernet8, peer_ip: 172.10.1.3/31}
    - {port: Ethernet6, ip: 172.10.1.8/31 , peer: dc1-spine02, pport: Ethernet6, peer_ip: 172.10.1.9/31}
  dc1-spine02:
    - {port: Ethernet1, ip: 172.10.1.4/31 , peer: dc1-leaf01, pport: Ethernet9, peer_ip: 172.10.1.5/31}
    - {port: Ethernet2, ip: 172.10.1.6/31 , peer: dc1-leaf02, pport: Ethernet9, peer_ip: 172.10.1.7/31}
    - {port: Ethernet6, ip: 172.10.1.9/31 , peer: dc1-spine01, pport: Ethernet6, peer_ip: 172.10.1.8/31}
  dc2-leaf01:
    - {port: Ethernet8, ip: 172.11.1.1/31 , peer: dc2-spine01, pport: Ethernet1, peer_ip: 172.11.1.0/31}
    - {port: Ethernet9, ip: 172.11.1.5/31 , peer: dc2-spine02, pport: Ethernet1, peer_ip: 172.11.1.4/31}
  dc2-leaf02:
    - {port: Ethernet8, ip: 172.11.1.3/31 , peer: dc2-spine01, pport: Ethernet2, peer_ip: 172.11.1.2/31}
    - {port: Ethernet9, ip: 172.11.1.7/31 , peer: dc2-spine02, pport: Ethernet2, peer_ip: 172.11.1.6/31}
  dc2-spine01:
    - {port: Ethernet1, ip: 172.11.1.0/31 , peer: dc2-leaf01, pport: Ethernet8, peer_ip: 172.11.1.1/31}
    - {port: Ethernet2, ip: 172.11.1.2/31 , peer: dc2-leaf02, pport: Ethernet8, peer_ip: 172.11.1.3/31}
    - {port: Ethernet6, ip: 172.11.1.8/31 , peer: dc2-spine02, pport: Ethernet6, peer_ip: 172.11.1.9/31}
  dc2-spine02:
    - {port: Ethernet1, ip: 172.11.1.4/31 , peer: dc2-leaf01, pport: Ethernet9, peer_ip: 172.11.1.5/31}
    - {port: Ethernet2, ip: 172.11.1.6/31 , peer: dc2-leaf02, pport: Ethernet9, peer_ip: 172.11.1.7/31}
    - {port: Ethernet6, ip: 172.11.1.9/31 , peer: dc2-spine01, pport: Ethernet6, peer_ip: 172.11.1.8/31}

lo_ip:
  dc1-leaf01: { ip: 10.100.1.1/32, state: up }
  dc1-leaf02: { ip: 10.100.1.2/32, state: up }
  dc1-spine01: { ip: 10.100.1.254/32, state: up }
  dc1-spine02: { ip: 10.100.1.253/32, state: up }
  dc2-leaf01: { ip: 10.100.2.1/32, state: up }
  dc2-leaf02: { ip: 10.100.2.2/32, state: up }
  dc2-spine01: { ip: 10.100.2.254/32, state: up }
  dc2-spine02: { ip: 10.100.2.253/32, state: up }

mgmt_net:
   dc1-leaf01: { port: Management1 , ip: 172.20.1.35/28 } 
   dc1-leaf02: { port: Management1 , ip: 172.20.1.36/28 } 
   dc1-spine01: { port: Management1 , ip: 172.20.1.41/28 } 
   dc1-spine02: { port: Management1 , ip: 172.20.1.42/28 } 
   dc2-leaf01: { port: Management1 , ip: 172.20.2.35/28 } 
   dc2-leaf02: { port: Management1 , ip: 172.20.2.36/28 } 
   dc2-spine01: { port: Management1 , ip: 172.20.2.41/28 } 
   dc2-spine02: { port: Management1 , ip: 172.20.2.42/28 } 

# END ANSIBLE MANAGED BLOCK
