- name: Get VPC facts
  ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpc_facts
  tags:
    - vpc
    - igw
    - subnet
    - rt

- debug: var=vpc_facts

- block:
    - name: Extract VPC ID
      set_fact:
        vpc_id: "{{ vpc_facts.vpcs[0].id }}"
      tags:
        - vpc-id
        - igw
        - subnet
        - rt

    - name: Get Subnet facts
      ec2_vpc_subnet_facts:
        filters:
          vpc-id: "{{ vpc_id }}"
      register: vpc_subnet_facts
      tags: subnet

    - name: Extract Subnet IDs
      set_fact:
        subnet_ids: "{{subnet_ids | default({}) | combine({item.tags.Name: item.id}) }}"
      with_items: "{{vpc_subnet_facts.subnets}}"
      tags: subnet

    - name: Get IGW facts
      ec2_vpc_igw_facts:
        filters:
          attachment.vpc-id: "{{ vpc_id }}"
      register: vpc_igw_facts
      tags: igw
    - name: Extract IGW ID
      set_fact:
        igw_id: "{{ vpc_igw_facts.internet_gateways[0].internet_gateway_id }}"
      tags: igw

    - name: Get Route Table facts
      ec2_vpc_route_table_facts:
        filters:
          vpc-id: "{{ vpc_id }}"
      register: vpc_route_table_facts
      tags: rt
    - debug: var=vpc_route_table_facts
      tags: rt

    - name: Extract Route Table IDs
      set_fact:
        rt_id: "{{vpc_route_table_facts.route_tables[0].id }}"
      tags: rt

  when: vpc_facts.vpcs != []
