# BEGIN ANSIBLE MANAGED BLOCK
bgp_asn: 65400

bgp_peers:
    - local_as: 65400
      peer: 10.100.1.1
      remote_as: 65400
    - local_as: 65400
      peer: 10.100.1.2
      remote_as: 65400
    - local_as: 65400
      peer: 10.100.1.3
      remote_as: 65400
# END ANSIBLE MANAGED BLOCK
