---
- name: Push Configuration to JunOS Devices
  hosts: junos
  tasks:
    - name: "Enable NETCONF"
      junos_netconf:
        netconf_port: 830
        state: present
      vars:
        ansible_connection: network_cli
      tags: netconf

    - name: "Deploy Configuration"
      junos_config:
        src: "{{config_dir}}/{{ inventory_hostname }}.cfg"
      tags: deploy

    - name: "Rollback config"
      junos_config:
        rollback: "{{ rollback | default('1') | int }}"
      tags: rollback, never