tmp_dir: ./tmp
config_dir: ./configs



# BEGIN ANSIBLE MANAGED BLOCK
global: 
  bgp_asn: 65400
  core_subnet: 10.1.1.0/24
  dns:
  - 172.20.1.1
  - 172.20.1.15
  loopback_subnet: 10.100.1.0/24
  mgmt_gw: 172.20.1.1
  mgmt_prefixes:
  - 192.168.0.0/24
  - 10.8.0.0/24
  mtu: 1500
  netconf_port: 830
  ospf_area: 0
  ospf_pid: 1
  p2p_prefix: 31
  root_pwd: $1$ciI4raxU$XfCVzABJKdALim0aWVMql0
  setup: isp
  users:
  -   role: super-user
      ssh_key: ansible_ssh_key.pub
      username: admin
  -   hash: $1$mR940Z9C$ipX9sLKTRDeljQXvWFfJm1
      passwd: 14161C180506262E757A60
      role: super-user
      username: ansible

p2p_ip:
  mxp01:
    - {port: ge-0/0/0, ip: 10.1.1.2 , peer: mxpe01, pport: ge-0/0/0, peer_ip: 10.1.1.3}
    - {port: ge-0/0/1, ip: 10.1.1.4 , peer: mxpe02, pport: ge-0/0/0, peer_ip: 10.1.1.5}
    - {port: ge-0/0/3, ip: 10.1.1.0 , peer: mxp02, pport: ge-0/0/3, peer_ip: 10.1.1.1}
  mxp02:
    - {port: ge-0/0/0, ip: 10.1.1.8 , peer: mxpe01, pport: ge-0/0/1, peer_ip: 10.1.1.9}
    - {port: ge-0/0/1, ip: 10.1.1.10 , peer: mxpe02, pport: ge-0/0/1, peer_ip: 10.1.1.11}
    - {port: ge-0/0/3, ip: 10.1.1.1 , peer: mxp01, pport: ge-0/0/3, peer_ip: 10.1.1.0}
  mxpe01:
    - {port: ge-0/0/0, ip: 10.1.1.3 , peer: mxp01, pport: ge-0/0/0, peer_ip: 10.1.1.2}
    - {port: ge-0/0/1, ip: 10.1.1.9 , peer: mxp02, pport: ge-0/0/0, peer_ip: 10.1.1.8}
  mxpe02:
    - {port: ge-0/0/0, ip: 10.1.1.5 , peer: mxp01, pport: ge-0/0/1, peer_ip: 10.1.1.4}
    - {port: ge-0/0/1, ip: 10.1.1.11 , peer: mxp02, pport: ge-0/0/1, peer_ip: 10.1.1.10}

lo_ip:
  mxp01: 10.100.1.254/32
  mxp02: 10.100.1.253/32
  mxpe01: 10.100.1.1/32
  mxpe02: 10.100.1.2/32

mgmt_net:
  mxp01:
      ip: 172.20.1.2/28
      port: em0
  mxp02:
      ip: 172.20.1.6/28
      port: fxp0
  mxpe01:
      ip: 172.20.1.3/28
      port: em0
  mxpe02:
      ip: 172.20.1.4/28
      port: em0


bgp_topo:
  af:
  - inet
  - inet-vpn
  peers:
      mxp01:
      - mxpe01
      - mxpe02
      mxpe01:
      - mxp01
      mxpe02:
      - mxp01
      xrpe03:
      - mxp01
  rr: mxp01
# END ANSIBLE MANAGED BLOCK